version: 2
jobs:
    build:
        machine: true
        steps:
            - checkout
            - run: make build
            - run: make image
            - run: make publish
            - run: make clean
