version: 2
jobs:
    build:
        docker:
          - image: circleci/golang:1
        steps:
            - checkout
            - run: go get -v -t -d ./...
            - run: sudo apt-get update
            - run: sudo apt remove yarn
            - run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            - run: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            - run: sudo apt-get update && sudo apt-get install yarn
            - run: touch .env
            - run: pwd
            - run: ls
            - run: make
