version: 2
jobs:
    build:
        docker:
          - image: circleci/golang:1
        steps:
            - checkout
            - run: go get -v -t -d ./...
            - run: curl https://npmjs.org/install.sh | sh
            - run: npm install -g yarn@0.18.1
            - run: touch .env
            - run: make
