version: 2
jobs:
    build:
        machine: true
        # docker:
        #     - image: circleci/golang:latest
        steps:
            - checkout
            # - setup_remote_docker
            - run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            - run: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            - run: sudo apt-get update && sudo apt-get install yarn
            - run: make install
            - run: ls /usr/local/go/src/vendor
            - run: ls /home/circleci/.go_workspace/src/github.com
            # - run: ls /home/circleci/.go_workspace/src/github.com
            # - run: cp -a /usr/local/go/src/vendor /usr/local/go/src
            - run: make build
            - run: make image
            - run: make publish
            - run: make clean
